apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scorpio-ingress
  labels:
    app: {{ template "appname" . }}
    service: broker
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
spec:
  backend:
    serviceName: scorpio
    servicePort: 9090
