apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}
