apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
    kompose.version: 1.20.0 ()
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    service: postgres
  name: postgres-deployment
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      release: {{ .Release.Name }}
      service: postgres
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
        service: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        env:
        - name: POSTGRES_DB
          value: ngb
        - name: POSTGRES_PASSWORD
          value: ngb
        - name: POSTGRES_USER
          value: ngb
        ports:
        - containerPort: 5432
        resources:
{{ toYaml .Values.postgres.resources | indent 12 }}
      restartPolicy: Always
      enableServiceLinks: false
