apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    app: {{ template "appname" . }}
    service: postgres
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
  name: postgres-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        app: {{ template "appname" . }}
        service: postgres
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: postgres
        image: mdillon/postgis
        env:
        - name: POSTGRES_DB
          value: ngb
        - name: POSTGRES_PASSWORD
          value: ngb
        - name: POSTGRES_USER
          value: ngb
        ports:
        - containerPort: 5432
      restartPolicy: Always
      enableServiceLinks: false
