apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    app: {{ template "appname" . }}
    service: broker
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
  name: scorpio
spec:
  ports:
  - name: scorpio-port
    port: 9090
    targetPort: 9090
  selector:
    app: {{ template "appname" . }}
    service: broker
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
  type: NodePort
    nodePort: 9090
status:
  loadBalancer: {}
