apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: scorpio
  name: scorpio-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: scorpio
    spec:
      containers:
      - name: scorpio
        image: scorpiobroker-aaio
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        resources: {}
      restartPolicy: Always
      enableServiceLinks: false
status: {}
