apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    app: {{ template "appname" . }}
    service: zookeeper
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
  name: zookeeper-deployment
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-aaio-dev.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        app: {{ template "appname" . }}
        service: zookeeper
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: zookeeper
        image: zookeeper
        ports:
        - containerPort: 2181
      restartPolicy: Always
      enableServiceLinks: false
